commits.message = "Update ${artifactName} to ${nextVersion}"

pullRequests.frequency = "1 day"

pullRequests.grouping = [
  {
    name = "typelevel"
    title = "Typelevel dependency updates"
    filter = [
      { group = "org.typelevel" },
      { group = "ch.epfl.scala" },
      { group = "org.scalameta" }
    ]
  }
]
