package fix.hkt

import java.nio.charset.StandardCharsets

import munit.FunSuite

import scalafix.v1.Symbol

final class CatsIndexSuite extends FunSuite {

  private lazy val index: CatsIndex = CatsIndex.load()

  test("isAncestor is transitive over the Cats lattice, and not symmetric") {
    assert(index.isAncestor(Symbol("cats/Functor#"), Symbol("cats/Monad#")))
    assert(!index.isAncestor(Symbol("cats/Monad#"), Symbol("cats/Functor#")))
  }

  test("resolveSyntax resolves Functor.Ops#map() to the Functor#map() owner") {
    val capability =
      index
        .resolveSyntax(Symbol("cats/Functor.Ops#map()."))
        .getOrElse(fail("no capability"))
    assertEquals(capability.owner, Symbol("cats/Functor#map()."))
  }

  test("syntaxImport resolves a RequiredOp owner to its direct syntax module") {
    assertEquals(
      index.syntaxImport(Symbol("cats/Functor#map().")),
      Some("cats.syntax.functor.*")
    )
    assertEquals(
      index.syntaxImport(Symbol("cats/Traverse#traverse().")),
      Some("cats.syntax.traverse.*")
    )
  }

  test("resolveStdlib resolves List#map() to the Functor#map() owner") {
    val capabilities =
      index.resolveStdlib(Symbol("scala/collection/immutable/List#map()."))
    assertEquals(capabilities.map(_.owner), List(Symbol("cats/Functor#map().")))
  }

  test("resolveStdlib keeps the two unrelated reduce capability roots") {
    val capabilities =
      index.resolveStdlib(Symbol("scala/collection/IterableOnceOps#reduce()."))
    assertEquals(capabilities.size, 2)
    assertEquals(
      capabilities.map(_.typeclass),
      List(Symbol("cats/Reducible#"), Symbol("cats/kernel/Semigroup#"))
    )
    val List(left, right) = capabilities.map(_.typeclass): @unchecked
    assert(!index.isAncestor(left, right))
    assert(!index.isAncestor(right, left))
  }

  test("resolveStdlib declines concrete-only operations") {
    assertEquals(
      index.resolveStdlib(Symbol("scala/collection/immutable/List#head().")),
      Nil
    )
    val deliberatelyAbsent = List(
      "head",
      "tail",
      "last",
      "apply",
      "sorted",
      "sortBy",
      "length",
      "size",
      "isDefined",
      "get",
      "reverse",
      "distinct",
      "zipWithIndex"
    )
    assert(
      index.stdlib.keysIterator.forall { symbol =>
        deliberatelyAbsent.forall(name => !symbol.value.contains(s"#$name("))
      }
    )
  }

  test("every stdlib owner and method pair exists in capabilities.tsv") {
    val capabilityPairs = index.capabilities.valuesIterator.flatten
      .map(capability => capability.owner -> capability.method)
      .toSet
    val stdlibPairs = resourceDataRows(CatsIndex.stdlibResource).map { line =>
      val cells = line.split("\t", -1)
      Symbol(cells(1)) -> Symbol(cells(2))
    }
    stdlibPairs.foreach(pair => assert(capabilityPairs(pair), pair.toString))
  }

  test("primitiveOwner and providersOf agree for Traverse#traverse()") {
    val method = Symbol("cats/Traverse#traverse().")
    assertEquals(index.primitiveOwner(method), Some(method))
    assert(index.providersOf(method).nonEmpty)
  }

  test("Bifunctor is indexed as Binary kind, and Binary has arity 2") {
    val bifunctor = index.typeclasses(Symbol("cats/Bifunctor#"))
    assertEquals(bifunctor.kind, KindShape.Binary)
    assertEquals(KindShape.arity(KindShape.Binary), 2)
  }

  test(
    "typeclasses.size matches the non-comment line count of typeclasses.tsv"
  ) {
    val bytes = getClass.getClassLoader
      .getResourceAsStream(CatsIndex.typeclassesResource)
      .readAllBytes()
    val lines = new String(bytes, StandardCharsets.UTF_8).split("\n", -1).toList
    val dataLineCount =
      lines.count(line => line.nonEmpty && !line.startsWith("#"))
    assertEquals(index.typeclasses.size, dataLineCount)
  }

  test("KindShape.render/parse round-trips for every shape") {
    List(KindShape.Star, KindShape.Unary, KindShape.Binary).foreach { shape =>
      assertEquals(KindShape.parse(KindShape.render(shape)), Some(shape))
    }
  }

  test("parse fails loudly on a malformed row, naming the resource and line") {
    val typeclassRows = Iterator(
      "#symbol\tparents\tkind\ttypeParams\tdepth\trenderName\timportPath\tpublic",
      "# generated by CatsIndexGen; do not edit by hand; source: org.typelevel::cats-core:2.13.0 for Scala 3.8.4; extraction: TASTy",
      "cats/Functor#\t\tNotAKind\t1\t1\tFunctor\tcats.Functor\ttrue"
    )
    val capabilityRows = Iterator.empty[String]
    val syntaxRows = Iterator.empty[String]
    val stdlibRows = Iterator.empty[String]

    val result =
      CatsIndex.parse(typeclassRows, capabilityRows, syntaxRows, stdlibRows)
    result match {
      case Left(message) =>
        assert(message.contains(CatsIndex.typeclassesResource))
        assert(message.contains(":3:"))
      case Right(_) => fail("expected a Left for a malformed kind token")
    }
  }

  private def resourceDataRows(resource: String): List[String] = {
    val stream = getClass.getClassLoader.getResourceAsStream(resource)
    try {
      new String(stream.readAllBytes(), StandardCharsets.UTF_8)
        .split("\n", -1)
        .toList
        .filter(line => line.nonEmpty && !line.startsWith("#"))
    } finally stream.close()
  }
}
