package fix.hkt

import java.nio.charset.StandardCharsets

import munit.FunSuite

import scalafix.v1.Symbol

final class CatsIndexSuite extends FunSuite {

  private lazy val index: CatsIndex = CatsIndex.load()

  test("isAncestor is transitive over the Cats lattice, and not symmetric") {
    assert(index.isAncestor(Symbol("cats/Functor#"), Symbol("cats/Monad#")))
    assert(!index.isAncestor(Symbol("cats/Monad#"), Symbol("cats/Functor#")))
  }

  test("resolveSyntax resolves Functor.Ops#map() to the Functor#map() owner") {
    val capability =
      index.resolveSyntax(Symbol("cats/Functor.Ops#map().")).getOrElse(fail("no capability"))
    assertEquals(capability.owner, Symbol("cats/Functor#map()."))
  }

  test("primitiveOwner and providersOf agree for Traverse#traverse()") {
    val method = Symbol("cats/Traverse#traverse().")
    assertEquals(index.primitiveOwner(method), Some(method))
    assert(index.providersOf(method).nonEmpty)
  }

  test("Bifunctor is indexed as Binary kind, and Binary has arity 2") {
    val bifunctor = index.typeclasses(Symbol("cats/Bifunctor#"))
    assertEquals(bifunctor.kind, KindShape.Binary)
    assertEquals(KindShape.arity(KindShape.Binary), 2)
  }

  test("typeclasses.size matches the non-comment line count of typeclasses.tsv") {
    val bytes = getClass.getClassLoader
      .getResourceAsStream(CatsIndex.typeclassesResource)
      .readAllBytes()
    val lines = new String(bytes, StandardCharsets.UTF_8).split("\n", -1).toList
    val dataLineCount = lines.count(line => line.nonEmpty && !line.startsWith("#"))
    assertEquals(index.typeclasses.size, dataLineCount)
  }

  test("KindShape.render/parse round-trips for every shape") {
    List(KindShape.Star, KindShape.Unary, KindShape.Binary).foreach { shape =>
      assertEquals(KindShape.parse(KindShape.render(shape)), Some(shape))
    }
  }

  test("parse fails loudly on a malformed row, naming the resource and line") {
    val typeclassRows = Iterator(
      "#symbol\tparents\tkind\ttypeParams\tdepth\trenderName\timportPath\tpublic",
      "# generated by CatsIndexGen; do not edit by hand; source: org.typelevel::cats-core:2.13.0 for Scala 3.8.4; extraction: TASTy",
      "cats/Functor#\t\tNotAKind\t1\t1\tFunctor\tcats.Functor\ttrue"
    )
    val capabilityRows = Iterator.empty[String]
    val syntaxRows = Iterator.empty[String]

    val result = CatsIndex.parse(typeclassRows, capabilityRows, syntaxRows)
    result match {
      case Left(message) =>
        assert(message.contains(CatsIndex.typeclassesResource))
        assert(message.contains(":3:"))
      case Right(_) => fail("expected a Left for a malformed kind token")
    }
  }
}
