package fix

/** Renders/parses `findings.tsv` (spec
  * 2026-09-20-diagnostic-instruction-table-design §1): a header line
  * `# purrism <version>` followed by one tab-separated row per [[Finding]],
  * sorted by code. Checked in twice (`docs/`, `scalafix/resources/purrism/`)
  * and regenerated by `mill scalafix.findings`; `mill scalafix.findingsCheck`
  * guards staleness.
  */
object FindingsTsv {

  /** A kind is lower-case kebab-case: `readability-budget`, `manual-resource`.
    */
  private val kindPattern = """^[a-z0-9]+(-[a-z0-9]+)*$""".r

  def render(version: String, findings: List[Finding]): String =
    (s"# purrism $version" :: findings
      .sortBy(_.code)
      .map(f =>
        List(f.code, f.rule, f.title, f.explanation, f.instruction, f.doc)
          .mkString("\t")
      )).mkString("", "\n", "\n")

  def parse(text: String): Either[String, (String, List[Finding])] = {
    val lines = text.linesIterator.toList
    lines match {
      case h :: rows if h.startsWith("# purrism ") =>
        val parsed = rows.filter(_.nonEmpty).map { r =>
          r.split("\t", -1) match {
            case Array(code, rule, title, expl, instr, doc) =>
              if (!code.startsWith(rule + "."))
                Left(s"code $code does not start with $rule.")
              else {
                val kind = code.stripPrefix(rule + ".")
                if (!kindPattern.matches(kind))
                  Left(s"code $code: kind '$kind' is not kebab-case")
                else Right(Finding(rule, kind, title, expl, instr, doc))
              }
            case other => Left(s"bad row (${other.length} fields): $r")
          }
        }
        parsed
          .collectFirst { case Left(e) => e }
          .toLeft(
            (h.stripPrefix("# purrism "), parsed.collect { case Right(f) => f })
          )
      case _ => Left("missing '# purrism <version>' header")
    }
  }
}
